---
abstract: 'Apache SpamAssassin is an extensible email filter which is used to identify spam'
author:
  - 'The Apache SpamAssassin Project <dev@spamassassin.apache.org>'
build_requires:
  Devel::Cycle: '0'
  ExtUtils::MakeMaker: '6.64'
  Perl::Critic::Policy::Perlsecret: '0'
  Perl::Critic::Policy::TestingAndDebugging::ProhibitNoStrict: '0'
  Test::More: '0'
  Text::Diff: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-SpamAssassin
no_index:
  directory:
    - t
    - inc
recommends:
  Archive::Zip: '0'
  BSD::Resource: '0'
  Compress::Zlib: '0'
  DBD::SQLite: '1.5901'
  DBI: '0'
  DB_File: '0'
  Email::Address::XS: '0'
  Encode::Detect::Detector: '0'
  Geo::IP: '0'
  IO::Socket::INET6: '0'
  IO::Socket::IP: '0.09'
  IO::Socket::SSL: '1.76'
  IO::String: '0'
  IP::Country::DB_File: '0'
  IP::Country::Fast: '0'
  LWP::UserAgent: '0'
  MIME::Base64: '0'
  Mail::DKIM: '0.37'
  Mail::DMARC: '0'
  Mail::SPF: '0'
  MaxMind::DB::Reader: '0'
  MaxMind::DB::Reader::XS: '0'
  Net::CIDR::Lite: '0'
  Net::LibIDN: '0'
  Net::LibIDN2: '0'
  Net::Patricia: '1.16'
  Net::SMTP: '0'
  Razor2::Client::Agent: '2.61'
requires:
  Archive::Tar: '1.23'
  Errno: '0'
  File::Copy: '2.02'
  File::Spec: '0.8'
  HTML::Parser: '3.43'
  IO::Zlib: '1.04'
  Mail::DKIM: '0.31'
  Net::DNS: '0.69'
  NetAddr::IP: '4.01'
  Pod::Usage: '1.1'
  Sys::Hostname: '0'
  Time::HiRes: '0'
  Time::Local: '0'
  perl: '5.014'
resources:
  MailingList: http://wiki.apache.org/spamassassin/MailingLists
  homepage: https://spamassassin.apache.org/
  license: http://www.apache.org/licenses/LICENSE-2.0.html
  repository: http://svn.apache.org/repos/asf/spamassassin/
version: '4.000000'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
